using RaniaAmer_Pharmacy.MVC.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace RaniaAmer_Pharmacy.MVC.Data.Configurations;

public class OrderConfiguration : IEntityTypeConfiguration<Order>
{
    public void Configure(EntityTypeBuilder<Order> builder)
    {
        builder.ToTable("Orders");

        builder.HasKey(o => o.Id);

        // A short, human-friendly sequential number (separate from the Guid Id) for customers
        // and staff to reference an order by ("order #42") — generated by the database.
        builder.Property(o => o.OrderNumber)
            .UseIdentityColumn()
            .ValueGeneratedOnAdd();

        builder.HasIndex(o => o.OrderNumber)
            .IsUnique();

        builder.Property(o => o.IsCredit)
            .IsRequired();

        builder.Property(o => o.Notes)
            .HasMaxLength(500);

        builder.Property(o => o.Status)
            .HasConversion<int>()
            .IsRequired();

        builder.Property(o => o.OrderDate)
            .IsRequired();

        builder.Property(o => o.CreatedAt)
            .IsRequired();

        // Supports the data-retention/pruning background job, which scans oldest-first at scale.
        builder.HasIndex(o => o.CreatedAt);

        builder.Property(o => o.UpdatedAt);

        builder.Ignore(o => o.Total);
        builder.Ignore(o => o.AmountPaid);
        builder.Ignore(o => o.RemainingBalance);
        builder.Ignore(o => o.IsFullyPaid);

        builder.Metadata.FindNavigation(nameof(Order.Items))!
            .SetPropertyAccessMode(PropertyAccessMode.Field);

        builder.Metadata.FindNavigation(nameof(Order.Payments))!
            .SetPropertyAccessMode(PropertyAccessMode.Field);

        builder.HasOne(o => o.Customer)
            .WithMany()
            .HasForeignKey(o => o.CustomerId)
            .OnDelete(DeleteBehavior.Restrict);

        builder.HasMany(o => o.Items)
            .WithOne(i => i.Order)
            .HasForeignKey(i => i.OrderId)
            .OnDelete(DeleteBehavior.Cascade);

        builder.HasMany(o => o.Payments)
            .WithOne(p => p.Order)
            .HasForeignKey(p => p.OrderId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}
